### ISSUE TITLE
Add the attraction tourist place and their info of places.

### ISSUE THREAD

**Issue by GojoSatoru12376** [GojoSatoru12376/Tourism#4]
Add the attraction tourist place and their info of places like Andhra Pradesh, Bihar , Goa , Gujarat , Himachal Pradesh and Karnataka

**Comment by GojoSatoru12376** [comment]
I would like to work on this issue.

**Comment by dishaa733** [comment]
I would like to work on this issue

**Comment by GojoSatoru12376** [comment]
Sure. Go ahead
